routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['/password/reset'=>false]);
// Route::get('/clear-cache', function() {
//     $exitCode = Artisan::call('config:clear');
//     $exitCode = Artisan::call('cache:clear');
//     $exitCode = Artisan::call('config:cache');
//     return 'DONE'; //Return anything
// });
Route::group(['prefix' => 'admin','middleware' => ['auth']], function() {
Route::get('/manage', 'HomeController@index')->name('home');


Route::group(['prefix' => 'enquiry','as' => 'enquiry.'], function() {
      Route::get('enquiry', 'Admin\EnquiryController@list')->name('list');
    Route::get('quick-enquiry', 'Admin\EnquiryController@list')->name('quick.enquiry');
    Route::get('quick-enquiries', 'Admin\EnquiryController@quick_enquiries')->name('quick');
    Route::get('quick-enquiries-view/{id}', 'Admin\EnquiryController@quick_enquiries_view')->name('quick.view');
    Route::get('quick-enquiry-delete/{id}', 'Admin\EnquiryController@quick_enquiry_delete')->name('quick.delete');
    Route::get('upcoming-course-enquiry', 'Admin\EnquiryController@upcoming_course_enquiry')->name('upcoming');
    Route::get('upcoming-course-delete/{id}', 'Admin\EnquiryController@upcoming_course_delete')->name('upcoming.delete');
    Route::get('upcoming-enquiries-view/{id}', 'Admin\EnquiryController@upcoming_course_view')->name('upcoming.view');
    Route::get('six-sigma-enquiry', 'Admin\EnquiryController@six_sigma_enquiry')->name('sixsigma');
    Route::get('six-signa-enquiries-view/{id}', 'Admin\EnquiryController@sigma_enquiry_view')->name('sigma.view');
    Route::get('six-sigma-delete/{id}', 'Admin\EnquiryController@six_sigma_delete')->name('upcoming.delete');
    Route::get('hrci-enquiry', 'Admin\EnquiryController@hrci_enquiry')->name('hrci');
    Route::get('hrci-enquiries-view/{id}', 'Admin\EnquiryController@hrci_enquiry_view')->name('hrci.view');
    Route::get('hrci-enquiry-delete/{id}', 'Admin\EnquiryController@hrci_delete')->name('hrci.delete');
    Route::get('cips-enquiry', 'Admin\EnquiryController@cips_enquiry')->name('cips');
    Route::get('cips-enquiries-view/{id}', 'Admin\EnquiryController@cips_enquiry_view')->name('cips.view');
    Route::get('cips-enquiry-delete/{id}', 'Admin\EnquiryController@cips_delete')->name('cips.delete');
    Route::get('brochure-request', 'Admin\EnquiryController@brochure')->name('brochure');
    Route::get('brochure-enquiries-view/{id}', 'Admin\EnquiryController@brochure_enquiry_view')->name('brochure.view');
    Route::get('brochure-delete/{id}', 'Admin\EnquiryController@brochure_delete')->name('brochure.delete');
    Route::get('calender-request', 'Admin\EnquiryController@calender')->name('calender');
    Route::get('calender-enquiries-view/{id}', 'Admin\EnquiryController@calender_enquiry_view')->name('calender.view');
    Route::get('calender-delete/{id}', 'Admin\EnquiryController@calender_delete')->name('calender.delete');
    Route::get('become-partner', 'Admin\EnquiryController@partner')->name('partner');
    Route::get('partner-enquiries-view/{id}', 'Admin\EnquiryController@partner_enquiry_view')->name('partner.view');
    Route::get('become-partner-delete/{id}', 'Admin\EnquiryController@partner_enquiry_delete')->name('partner.delete');
    Route::get('certificate-card-verification', 'Admin\EnquiryController@certificate')->name('certificate');
    Route::get('certificate-enquiries-view/{id}', 'Admin\EnquiryController@certificate_enquiry_view')->name('certificate.view');
    Route::get('certificate-card-verification-delete/{id}', 'Admin\EnquiryController@certificate_enquiry_delete')->name('certificate.delete');
    Route::get('contact-enquiries', 'Admin\EnquiryController@contact_enquiry')->name('contact');
    Route::get('contact-enquiries-view/{id}', 'Admin\EnquiryController@contact_enquiry_view')->name('contact.view');
    Route::get('contact-enquiries-delete/{id}', 'Admin\EnquiryController@contact_enquiry_delete')->name('contact.delete');

    Route::get('offers', 'Admin\EnquiryController@offers')->name('offers');
    Route::get('offers-enquiries-view/{id}', 'Admin\EnquiryController@offers_enquiry_view')->name('offers.view');
    Route::get('offers-delete/{id}', 'Admin\EnquiryController@offers_enquiry_delete')->name('offers.delete');
});
Route::group(['prefix' => 'courses'], function() {
Route::get('category', 'Admin\CategoryController@index')->name('admin.category');
Route::get('category-new', 'Admin\CategoryController@new')->name('category.new');
Route::post('category-save', 'Admin\CategoryController@save')->name('category.save');
Route::get('category-edit/{id}', 'Admin\CategoryController@edit')->name('category.edit');
Route::post('category-update','Admin\CategoryController@update')->name('category.update');
Route::get('category-delete/{id}', 'Admin\CategoryController@delete')->name('category.delete');
Route::get('category-view/{id}', 'Admin\CategoryController@view')->name('category.view');

Route::get('courses', 'Admin\CourseController@index')->name('admin.courses');
Route::get('courses-new', 'Admin\CourseController@new')->name('courses.new');
Route::post('courses-save', 'Admin\CourseController@save')->name('courses.save');
Route::get('courses-edit/{id}', 'Admin\CourseController@edit')->name('courses.edit');
Route::post('courses-update','Admin\CourseController@update')->name('courses.update');
Route::get('courses-delete/{id}', 'Admin\CourseController@delete')->name('courses.delete');
Route::get('courses-view/{id}', 'Admin\CourseController@view')->name('courses.view');

Route::get('coursedetails', 'Admin\CourseDetailsController@index')->name('admin.coursedetails');
Route::get('coursedetails-new', 'Admin\CourseDetailsController@new')->name('coursedetails.new');
Route::post('coursedetails-save', 'Admin\CourseDetailsController@save')->name('coursedetails.save');
Route::get('coursedetails-edit/{id}', 'Admin\CourseDetailsController@edit')->name('coursedetails.edit');
Route::post('coursedetails-update','Admin\CourseDetailsController@update')->name('coursedetails.update');
Route::get('coursedetails-delete/{id}', 'Admin\CourseDetailsController@delete')->name('coursedetails.delete');
Route::get('coursedetails-view/{id}', 'Admin\CourseDetailsController@view')->name('coursedetails.view');



Route::get('six-sigma-courses', 'Admin\SixSigmaCourseController@index')->name('sigma.index');
Route::get('sigma-new', 'Admin\SixSigmaCourseController@new')->name('sigma.new');
Route::post('sigma-save', 'Admin\SixSigmaCourseController@save')->name('sigma.save');
Route::get('sigma-edit/{id}', 'Admin\SixSigmaCourseController@edit')->name('sigma.edit');
Route::post('sigma-update','Admin\SixSigmaCourseController@update')->name('sigma.update');
Route::get('sigma-delete/{id}', 'Admin\SixSigmaCourseController@delete')->name('sigma.delete');
Route::get('sigma-view/{id}', 'Admin\SixSigmaCourseController@view')->name('sigma.view');

Route::get('hrci-courses', 'Admin\HrciCourseController@index')->name('hrci.index');
Route::get('hrci-new', 'Admin\HrciCourseController@new')->name('hrci.new');
Route::post('hrci-save', 'Admin\HrciCourseController@save')->name('hrci.save');
Route::get('hrci-edit/{id}', 'Admin\HrciCourseController@edit')->name('hrci.edit');
Route::post('hrci-update','Admin\HrciCourseController@update')->name('hrci.update');
Route::get('hrci-delete/{id}', 'Admin\HrciCourseController@delete')->name('hrci.delete');
Route::get('hrci-view/{id}', 'Admin\HrciCourseController@view')->name('hrci.view');

Route::get('cips-certification', 'Admin\CipsCourseController@index')->name('cips.index');
Route::get('cips-new', 'Admin\CipsCourseController@new')->name('cips.new');
Route::post('cips-save', 'Admin\CipsCourseController@save')->name('cips.save');
Route::get('cips-edit/{id}', 'Admin\CipsCourseController@edit')->name('cips.edit');
Route::post('cips-update','Admin\CipsCourseController@update')->name('cips.update');
Route::get('cips-delete/{id}', 'Admin\CipsCourseController@delete')->name('cips.delete');
Route::get('cips-view/{id}', 'Admin\CipsCourseController@view')->name('cips.view');
 });

Route::group(['prefix' => 'manage'], function() {
Route::get('cms-pages', 'Admin\CmsPageController@index')->name('cms.index');
Route::get('cms-new', 'Admin\CmsPageController@new')->name('cms.new');
Route::post('cms-save', 'Admin\CmsPageController@save')->name('cms.save');
Route::get('cms-edit/{id}', 'Admin\CmsPageController@edit')->name('cms.edit');
Route::post('cms-update','Admin\CmsPageController@update')->name('cms.update');
Route::get('cms-delete/{id}', 'Admin\CmsPageController@delete')->name('cms.delete');
Route::get('cms-view/{id}', 'Admin\CmsPageController@view')->name('cms.view');

Route::get('countries', 'Admin\CountryController@index')->name('country.index');
Route::get('country-new', 'Admin\CountryController@new')->name('country.new');
Route::post('country-save', 'Admin\CountryController@save')->name('country.save');
Route::get('country-edit/{id}', 'Admin\CountryController@edit')->name('country.edit');
Route::post('country-update','Admin\CountryController@update')->name('country.update');
Route::get('country-delete/{id}', 'Admin\CountryController@delete')->name('country.delete');
Route::get('country-view/{id}', 'Admin\CountryController@view')->name('country.view');

Route::get('cities', 'Admin\CityController@index')->name('city.index');
Route::get('city-new', 'Admin\CityController@new')->name('city.new');
Route::post('city-save', 'Admin\CityController@save')->name('city.save');
Route::get('city-edit/{id}', 'Admin\CityController@edit')->name('city.edit');
Route::post('city-update','Admin\CityController@update')->name('city.update');

resources/views/admin/themes/footer.blade.php
<footer class="main-footer">
 
    <strong>Copyright &copy; {{ date('Y')}} <a href="{{ env('APP_URL', '#')}}">{{ env('APP_NAME', 'TUV NORD TRAININGS')}}</a>.</strong> All rights
    reserved.
  </footer>


  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->

<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('public/admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('public/admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('public/admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('public/admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
{{-- <script src="{{ asset('public/admin/dist/js/demo.js') }}"></script> --}}
<script>
  $(document).ready(function () {
    $('.sidebar-menu').tree()
  })
</script>
 {{-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>   --}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> --}}
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

  
  
  
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 <script>
  $( function() {
    $( ".datepicker" ).datepicker();
  } );
  </script>
    <script>
    
      var table = $('.data-table-sigma').DataTable({
        //   dom: '<"ButtonStuff"B><"FilterStuff"f>t',
          processing: true,
          serverSide: true,
          ajax: "{{ route('sigma.index') }}",
          columns: [
              {data: 'DT_RowIndex', name: 'DT_RowIndex'},
              {data: 'name', name: 'name'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
    </script>

</body>
</html>

resources/views/admin/themes/header.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('public/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('public/admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ asset('public/admin/bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('public/admin/dist/css/AdminLTE.min.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('public/admin/dist/css/skins/_all-skins.min.css') }}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="{{ asset('public/admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
  @stack('scripts')
</head>
<body class="hold-transition skin-blue sidebar-mini" style="min-height:200px">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="{{route('home')}}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>{{ env('APP_SUB_NAME', 'TNT')}}</b></span>
      <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>{{ env('APP_NAME', 'TUV NORD TRAININGS')}}</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ asset('public/admin/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ asset('public/admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">

             
              </li>
              <!-- Menu Body -->
             
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                    <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                 Logout
                 </a>
                 <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                 </form>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        
        </ul>
      </div>
    </nav>
  </header>

resources/views/admin/themes/page_title_bar.blade.php
<section class="content-header">
    <h1>
    TUV
      <small>Manage</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{route('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Examples</a></li>
      <li class="active">Blank page</li>
    </ol>
  </section>

resources/views/admin/themes/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ asset('public/admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
     
          </a>
        </li>
        <li class="treeview {{ (Request::segment(2) == 'courses' ) ? 'active' : '' }}">
          <a href="#">
            <i class="fa fa-graduation-cap"></i> <span>Manage Courses</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
         <ul class="treeview-menu">
            <li class="{{ (Request::segment(3) == 'category' ) ? 'active' : '' }}"><a href="{{route('admin.category')}}"><i class="fa fa-circle-o"></i> Categories</a></li>          
            <li class="{{ (Request::segment(3) == 'courses' ) ? 'active' : '' }}"><a href="{{route('admin.courses')}}"><i class="fa fa-circle-o"></i> Courses</a></li>
            <li class="{{ (Request::segment(3) == 'coursedetails' ) ? 'active' : '' }}"><a href="{{route('admin.coursedetails')}}"><i class="fa fa-circle-o"></i> Course Details</a></li>
            <li class="{{ (Request::segment(3) == 'six-sigma-courses' ) ? 'active' : '' }}"><a href="{{route('sigma.index')}}"><i class="fa fa-circle-o"></i> Six Sigma</a></li>
            <li class="{{ (Request::segment(3) == 'hrci-courses' ) ? 'active' : '' }}"><a href="{{route('hrci.index')}}"><i class="fa fa-circle-o"></i> HRCI Manage</a></li>
            <li class="{{ (Request::segment(3) == 'cips-certification' ) ? 'active' : '' }}"><a href="{{route('cips.index')}}"><i class="fa fa-circle-o"></i> CIPS Manage</a></li>
          </ul>
        </li>
        <li class="treeview {{ (Request::segment(2) == 'manage' ) ? 'active' : '' }}">
          <a href="#">
            <i class="fa fa-sitemap"></i> <span>Manage</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="{{ (Request::segment(3) == 'cms-pages' ) ? 'active' : '' }}"><a href="{{route('cms.index')}}"><i class="fa fa-circle-o text-aqua"></i> CMS Manage</a></li>
            <li class="{{ (Request::segment(3) == 'cities' ) ? 'active' : '' }}"><a href="{{route('city.index')}}"><i class="fa fa-circle-o  text-aqua"></i> City</a></li>
            <li class="{{ (Request::segment(3) == 'currency' ) ? 'active' : '' }}"><a href="{{route('currency.index')}}"><i class="fa fa-circle-o  text-aqua"></i> Currency</a></li>
            <li class="{{ (Request::segment(3) == 'countries' ) ? 'active' : '' }}"><a href="{{route('country.index')}}"><i class="fa fa-circle-o  text-aqua"></i> Country</a></li>  
            <li class="{{ (Request::segment(3) == 'Clientele-index' ) ? 'active' : '' }}"><a href="{{route('clientele.index')}}"><i class="fa fa-circle-o text-aqua"></i> Clientele</a></li>
              <li class="{{ (Request::segment(3) == 'faq-index' ) ? 'active' : '' }}"><a href="{{route('faq.index')}}"><i class="fa fa-circle-o text-aqua"></i> FAQ</a></li>   
            <li class="{{ (Request::segment(3) == 'galleries' ) ? 'active' : '' }}"><a href="{{route('gallery.index')}}"><i class="fa fa-circle-o text-aqua"></i>  Gallery</a></li>
            <li class="{{ (Request::segment(3) == 'gallery-details' ) ? 'active' : '' }}"><a href="{{route('gallerydetail.index')}}"><i class="fa fa-circle-o text-aqua"></i>  Gallery Detail</a></li>
            <li class="{{ (Request::segment(3) == 'home-banner' ) ? 'active' : '' }}"><a href="{{route('home-banner')}}"><i class="fa fa-circle-o text-aqua"></i> Home Banner</a></li>
            <li class="{{ (Request::segment(3) == 'locations' ) ? 'active' : '' }}"><a href="{{route('locations')}}"><i class="fa fa-circle-o text-aqua"></i> Locations</a></li>
            <li class="{{ (Request::segment(3) == 'news' ) ? 'active' : '' }}"><a href="{{route('news.index')}}"><i class="fa fa-circle-o text-aqua"></i> News</a></li>
            <li class="{{ (Request::segment(3) == 'testimonial' ) ? 'active' : '' }}"><a href="{{route('testimonial')}}"><i class="fa fa-circle-o text-aqua"></i> Testimonial</a></li>
            <li class="{{ (Request::segment(3) == 'qualification' ) ? 'active' : '' }}"><a href="{{route('qualification.index')}}"><i class="fa fa-circle-o text-aqua"></i> Qualifications</a></li>
            <li class="{{ (Request::segment(3) == 'press-release-index' ) ? 'active' : '' }}"><a href="{{route('pressrelease.index')}}"><i class="fa fa-circle-o text-aqua"></i> Press Release</a></li>
            <li class="{{ (Request::segment(3) == 'appeciation-letter-index' ) ? 'active' : '' }}"><a href="{{route('appeciation.letter.index')}}"><i class="fa fa-circle-o text-aqua"></i> Appreciation Letter</a></li>
            <li class="{{ (Request::segment(3) == 'Webinar-index' ) ? 'active' : '' }}"><a href="{{route('webinar.index')}}"><i class="fa fa-circle-o text-aqua"></i> Webinar</a></li>
          </ul>
        </li>
       <li class="treeview {{ (Request::segment(2) == 'enquiry' ) ? 'active' : '' }} ">
          <a href="#">
            <i class="fa fa-share"></i> <span>Enquiries</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            {{-- <li><a href="{{route('enquiry.list')}}"><i class="fa fa-circle-o text-aqua"></i>  Enquiry</a></li> --}}
            <li class="{{ (Request::segment(3) == 'quick-enquiries' ) ? 'active' : '' }}"><a href="{{route('enquiry.quick')}}"><i class="fa fa-circle-o text-aqua"></i> Quick Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'contact-enquiries' ) ? 'active' : '' }}"><a href="{{route('enquiry.contact')}}"><i class="fa fa-circle-o text-aqua"></i> Contact Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'offers' ) ? 'active' : '' }}"><a href="{{route('enquiry.offers')}}"><i class="fa fa-circle-o text-aqua"></i> Offer Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'upcoming-course-enquiry' ) ? 'active' : '' }}"><a href="{{route('enquiry.upcoming')}}"><i class="fa fa-circle-o text-aqua"></i> Course Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'six-sigma-enquiry' ) ? 'active' : '' }}"><a href="{{route('enquiry.sixsigma')}}"><i class="fa fa-circle-o text-aqua"></i> Six sigma Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'hrci-enquiry' ) ? 'active' : '' }}"><a href="{{route('enquiry.hrci')}}"><i class="fa fa-circle-o text-aqua"></i> HRCI Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'cips-enquiry' ) ? 'active' : '' }}"><a href="{{route('enquiry.cips')}}"><i class="fa fa-circle-o text-aqua"></i> CIPS Enquiry</a></li>
            <li class="{{ (Request::segment(3) == 'brochure-request' ) ? 'active' : '' }}"><a href="{{route('enquiry.brochure')}}"><i class="fa fa-circle-o text-aqua"></i> Brochure Request</a></li>
            <li class="{{ (Request::segment(3) == 'calender-request' ) ? 'active' : '' }}"><a href="{{route('enquiry.calender')}}"><i class="fa fa-circle-o text-aqua"></i> Calender Request</a></li>
             <li class="{{ (Request::segment(3) == 'become-partner' ) ? 'active' : '' }}"><a href="{{route('enquiry.partner')}}"><i class="fa fa-circle-o text-aqua"></i> Become a Partner</a></li> 
            <li class="{{ (Request::segment(3) == 'certificate-card-verification' ) ? 'active' : '' }}"><a href="{{route('enquiry.certificate')}}"><i class="fa fa-circle-o text-aqua"></i> Card/Certificate</a></li>  
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>